server:
  port: 8083
spring:
  application:
    name: mall-canal
  cloud:
    nacos:
      config:
        file-extension: yaml
        server-addr: 47.98.181.113:8848
      discovery:
        #Nacos的注册地址
        server-addr: 47.98.181.113:8848
  main:
    allow-bean-definition-overriding: true
#日志配置
logging:
  pattern:
    console: "%msg%n"
  level:
    root: error

elaticjob:
  zookeeper:
    server-lists: 127.0.0.1:2181
    namespace: synctask

#动态定时任务案例
dynamiczk: 127.0.0.1:2181
dynamicnamespace: dynamictask