spring:
  application:
    name: eureka-feign-client
server:
  port: 8764
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/
feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true



